export {
    SET_RESTAURANTS_LOADING_FLAG,
    SET_RESTAURANTS_FAIL_FLAG,
    START_FETCH_RESTAURANTS,
    FETCH_RESTAURANTS,
    START_ADD_RESTAURANT,
    ADD_RESTAURANT,
    START_DELETE_RESTAURANT,
    DELETE_RESTAURANT,
    SELECT_RESTAURANT,
    START_FETCH_RESTAURANT,
    FETCH_RESTAURANT,
    START_UPDATE_RESTAURANT,
    UPDATE_RESTAURANT,
    CLEAR_RESTAURANTS_ERROR,
    CLEAR_SELECTED_RESTAURANT
} from './restaurants';